GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    
    "author":"sudesh12",
    "url":"12something.com",
    "likes":203
}

###
DELETE http://localhost:3001/api/blogs/113

###
PUT http://localhost:3001/api/blogs/12
Content-Type: application/json

{
    "likes":4
}


###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name":"ashwin",
    "username":"@ashwin"

}

###
GET http://localhost:3001/api/users


###
PUT http://localhost:3001/api/users/@sudesh
Content-Type:  application/json

{
    "name":"Sudesh"
}
