GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"another",
    "author":"sudesh1",
    "url":"1something.com",
    "likes":202
}

###
DELETE http://localhost:3001/api/blogs/16