GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"more blog",
    "author":"sudesh",
    "url":"something.com",
    "likes":12
}

###
DELETE http://localhost:3001/api/blogs/16